[options]
db_host = db
db_port = 5432
db_user = odoo
; use DB_PASSWORD_FILE via Docker secrets in compose.prod.yml
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
log_level = warning
logfile = False
xmlrpc_port = 8069
