[options]
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
log_level = debug
logfile = False
dev_mode = reload,qweb,werkzeug,xml
xmlrpc_port = 8069
